const NGSL_REMOTE='https://raw.githubusercontent.com/zhghx/qwerty-learner/0b29037/public/dicts/NGSL_1.2.json';
const DICT_API='https://api.dictionaryapi.dev/api/v2/entries/en/';
const TRANS_API='https://api.mymemory.translated.net/get?q=';
let chapterIndex=+(localStorage.getItem('river.chapter')||0); if(chapterIndex<0||chapterIndex>=CHAPTERS.length) chapterIndex=0;
let ngslDict=null, selected=null, currentSentenceText='', currentHead='';
let voices=[], speaking={active:false,paused:false,queue:[],index:0,mode:'chapter'};
const known=new Set(JSON.parse(localStorage.getItem('river.known')||'[]'));
const favs=new Set(JSON.parse(localStorage.getItem('river.favs')||'[]'));
const $=id=>document.getElementById(id);
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1500)}
function norm(s){return (s||'').toLowerCase().replace(/[“”]/g,'"').replace(/[‘’]/g,"'").replace(/\s+/g,' ').trim()}
function escapeHtml(s){return (s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function headFor(surface){let x=surface.toLowerCase().replace(/’/g,"'"); if(x.endsWith("'s")) x=x.slice(0,-2); return SURFACE_HEAD[x]||SURFACE_HEAD[surface.toLowerCase()]||x}
function splitSentences(text){if(window.Intl&&Intl.Segmenter){return [...new Intl.Segmenter('en',{granularity:'sentence'}).segment(text)].map(x=>x.segment).filter(x=>x.trim())} return text.match(/[^.!?]+[.!?]+[”’"']?|[^.!?]+$/g)||[text]}
function collocationsForSentence(sentence){const n=norm(sentence);return COLLOCATIONS.filter(x=>{const c=norm(x.context);return c===n || (c.length>35&&n.includes(c.slice(0,Math.min(70,c.length)))) || (n.length>35&&c.includes(n.slice(0,Math.min(70,n.length))))}).map(x=>x.pattern)}
function renderWords(s,sid){let out='', last=0; const re=/[A-Za-z]+(?:[’'][A-Za-z]+)*/g; let m; while((m=re.exec(s))){out+=escapeHtml(s.slice(last,m.index)); const w=m[0], h=headFor(w), cls=known.has(h)?'word known':'word'; out+=`<span class="${cls}" data-word="${escapeHtml(w)}" data-head="${escapeHtml(h)}" data-sid="${sid}">${escapeHtml(w)}</span>`; last=m.index+w.length} out+=escapeHtml(s.slice(last)); return out}
function renderChapter(i,restore=true,preserveSpeech=false){if(!preserveSpeech)stopSpeech(false); chapterIndex=i; localStorage.setItem('river.chapter',i); const ch=CHAPTERS[i]; $('topChapter').textContent=ch.title; $('reader').innerHTML=`<div class="chapter-kicker">Chapter ${i+1} of ${CHAPTERS.length}</div><h1>${escapeHtml(ch.title.replace(/^Chapter\s+\w+\s+—\s+/i,''))}</h1>`; let sid=0; ch.paragraphs.forEach(p=>{const para=document.createElement('p');para.className='para'; splitSentences(p).forEach(s=>{const sp=document.createElement('span');sp.className='sentence';sp.dataset.sid=String(sid);sp.dataset.text=s;sp.innerHTML=renderWords(s,sid);para.appendChild(sp);sid++});$('reader').appendChild(para)}); updateChapterList(); updateStats(); requestAnimationFrame(()=>{if(restore){let y=+(localStorage.getItem('river.scroll.'+i)||0);window.scrollTo(0,y)}else window.scrollTo(0,0);updateProgress()})}
function updateChapterList(){document.querySelectorAll('.chapter-btn').forEach((b,j)=>b.classList.toggle('active',j===chapterIndex))}
function openDrawer(){closeSettings();$('overlay').classList.add('show');$('drawer').classList.add('show')}
function closeDrawer(){$('drawer').classList.remove('show'); if(!$('wordSheet').classList.contains('show'))$('overlay').classList.remove('show')}
function openSheet(){$('overlay').classList.add('show');$('wordSheet').classList.add('show')}
function closeSheet(){$('wordSheet').classList.remove('show');document.querySelectorAll('.word.selected').forEach(x=>x.classList.remove('selected'));if(!$('drawer').classList.contains('show'))$('overlay').classList.remove('show')}
function closeSettings(){$('settings').classList.remove('show')}
function highlightWordInSentence(sentence,word){const re=new RegExp(`\\b(${word.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')})\\b`,'i');return escapeHtml(sentence).replace(re,'<mark>$1</mark>')}
async function loadDictionary(){try{const cached=localStorage.getItem('river.ngsl.dict'); if(cached){ngslDict=JSON.parse(cached);return} const r=await fetch(NGSL_REMOTE,{cache:'force-cache'}); if(!r.ok)throw 0; const arr=await r.json(); ngslDict={};arr.forEach(x=>ngslDict[x.name.toLowerCase()]={zh:x.trans?.[0]||'',def:x.trans?.[1]||''}); try{localStorage.setItem('river.ngsl.dict',JSON.stringify(ngslDict))}catch(e){} }catch(e){ngslDict={}}}
async function getOnlinePhonetic(head){try{const k='river.ipa.'+head,c=localStorage.getItem(k);if(c)return c;const r=await fetch(DICT_API+encodeURIComponent(head));if(!r.ok)return '';const j=await r.json();let p='';for(const e of j){p=e.phonetic||e.phonetics?.find(x=>x.text)?.text||'';if(p)break}if(p)localStorage.setItem(k,p);return p}catch(e){return ''}}
function contextualSense(head,sentence){const arr=POLY[head]||[];const n=norm(sentence); for(const x of arr){const c=norm(x.context); if(n===c||n.includes(c)||c.includes(n))return x.sense} return ''}
async function showWord(el){document.querySelectorAll('.word.selected').forEach(x=>x.classList.remove('selected'));el.classList.add('selected'); const surface=el.dataset.word,head=el.dataset.head||headFor(surface), sentence=el.closest('.sentence')?.dataset.text||'';selected={surface,head,sentence,el};currentSentenceText=sentence;currentHead=head;$('wordTitle').textContent=surface;$('ipa').textContent=IPA_FALLBACK[surface.toLowerCase()]||IPA_FALLBACK[head]||'…';$('wordContext').innerHTML=highlightWordInSentence(sentence,surface);$('sentenceZh').textContent=''; const cs=contextualSense(head,sentence); let d=ngslDict?.[head]; if(cs){$('senseBox').innerHTML=`<strong>本句义</strong><div class="zh">${escapeHtml(cs)}</div>${d?.def?`<div class="def">${escapeHtml(d.def)}</div>`:''}`}
 else if(d){$('senseBox').innerHTML=`<strong>常用义</strong><div class="zh">${escapeHtml(d.zh)}</div><div class="def">${escapeHtml(d.def)}</div>`}
 else {$('senseBox').innerHTML=`<strong>词义</strong><div class="zh">正在加载…</div><div class="def">若第一次打开，请保持联网以载入 NGSL 中文词典。</div>`; if(!ngslDict){await loadDictionary();d=ngslDict?.[head];if(selected?.head===head&&d)$('senseBox').innerHTML=`<strong>常用义</strong><div class="zh">${escapeHtml(d.zh)}</div><div class="def">${escapeHtml(d.def)}</div>`}}
 const csList=collocationsForSentence(sentence);$('collocSection').style.display=csList.length?'block':'none';$('collocChips').innerHTML=csList.map(c=>`<span class="chip">${escapeHtml(c)}</span>`).join('');$('knownBtn').textContent=known.has(head)?'✓ 已学':'✓ 标记已学';$('favBtn').textContent=favs.has(head)?'★ 已收藏':'☆ 收藏';openSheet(); const online=await getOnlinePhonetic(head);if(selected?.head===head&&online)$('ipa').textContent=online}
function chooseVoice(){const sel=$('voice').value;return voices.find(v=>v.name===sel)||voices.find(v=>/^en(-|_)/i.test(v.lang)&&/Samantha|Daniel|Karen|Moira|Ava|Alex/i.test(v.name))||voices.find(v=>/^en(-|_)/i.test(v.lang))||null}
function loadVoices(){voices=speechSynthesis.getVoices(); const eng=voices.filter(v=>/^en(-|_)/i.test(v.lang));$('voice').innerHTML=eng.map(v=>`<option value="${escapeHtml(v.name)}">${escapeHtml(v.name)} · ${escapeHtml(v.lang)}</option>`).join('');const saved=localStorage.getItem('river.voice'); if(saved&&eng.some(v=>v.name===saved))$('voice').value=saved}
function speakText(text,rate=null){if(!('speechSynthesis'in window)){toast('当前浏览器不支持系统朗读');return} speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=rate||(+($('rate').value)/100);const v=chooseVoice();if(v)u.voice=v;speechSynthesis.speak(u)}
function buildQueue(mode){let q=[];const start=mode==='all'?0:chapterIndex,end=mode==='all'?CHAPTERS.length:chapterIndex+1;for(let ci=start;ci<end;ci++){CHAPTERS[ci].paragraphs.forEach(p=>splitSentences(p).forEach(s=>q.push({ci,text:s}))) }return q}
function startSpeech(mode='chapter'){if(!('speechSynthesis'in window)){toast('当前浏览器不支持系统朗读');return} stopSpeech(false); speaking={active:true,paused:false,queue:buildQueue(mode),index:0,mode}; $('audioBar').classList.remove('hidden');$('audioTitle').textContent=mode==='all'?'全文朗读':'本章朗读'; speakNext()}
function speakNext(){if(!speaking.active||speaking.index>=speaking.queue.length){stopSpeech();return} const item=speaking.queue[speaking.index]; if(item.ci!==chapterIndex){renderChapter(item.ci,false,true)} requestAnimationFrame(()=>{document.querySelectorAll('.sentence.speaking').forEach(x=>x.classList.remove('speaking'));const sentences=[...document.querySelectorAll('.sentence')];const localIndex=speaking.queue.slice(0,speaking.index).filter(x=>x.ci===item.ci).length;const el=sentences[localIndex];if(el){el.classList.add('speaking');el.scrollIntoView({block:'center',behavior:'smooth'})}$('audioSentence').textContent=item.text;const u=new SpeechSynthesisUtterance(item.text);u.lang='en-US';u.rate=+($('rate').value)/100;const v=chooseVoice();if(v)u.voice=v;u.onend=()=>{if(!speaking.active)return;speaking.index++;speakNext()};u.onerror=()=>{if(!speaking.active)return;speaking.index++;speakNext()};speechSynthesis.speak(u)})}
function toggleSpeech(){if(!speaking.active)return;if(speaking.paused){speechSynthesis.resume();speaking.paused=false;$('audioToggle').textContent='Ⅱ'}else{speechSynthesis.pause();speaking.paused=true;$('audioToggle').textContent='▶'}}
function stopSpeech(show=true){if('speechSynthesis'in window)speechSynthesis.cancel();speaking.active=false;speaking.paused=false;document.querySelectorAll('.sentence.speaking').forEach(x=>x.classList.remove('speaking'));$('audioBar').classList.add('hidden');$('audioToggle').textContent='Ⅱ';if(show)toast('已停止朗读')}
async function translateSentence(){if(!currentSentenceText)return;const btn=$('translateSentence');btn.textContent='翻译中…';try{const key='river.sentzh.'+btoa(unescape(encodeURIComponent(currentSentenceText))).slice(0,80);let z=localStorage.getItem(key);if(!z){const r=await fetch(TRANS_API+encodeURIComponent(currentSentenceText)+'&langpair=en|zh-CN');const j=await r.json();z=j.responseData?.translatedText||'';if(z)localStorage.setItem(key,z)}$('sentenceZh').textContent=z||'暂时没有获取到翻译。'}catch(e){$('sentenceZh').textContent='联网后可以翻译整句。'}finally{btn.textContent='翻译本句'}}
function updateProgress(){const doc=document.documentElement;const max=doc.scrollHeight-innerHeight;const pct=max>0?scrollY/max*100:0;$('progress').style.width=Math.min(100,Math.max(0,pct))+'%';localStorage.setItem('river.scroll.'+chapterIndex,String(Math.round(scrollY)))}
function updateStats(){$('stats').textContent=`已学 ${known.size} 个 · 收藏 ${favs.size} 个 · 共 ${CHAPTERS.length} 章`}
function applyPrefs(){const fs=localStorage.getItem('river.font')||19,lh=localStorage.getItem('river.lh')||188,rate=localStorage.getItem('river.rate')||88,theme=localStorage.getItem('river.theme')||'light';$('fontSize').value=fs;$('lineHeight').value=lh;$('rate').value=rate;$('rateText').textContent=(rate/100).toFixed(2)+'×';document.documentElement.style.setProperty('--font',fs+'px');document.documentElement.style.setProperty('--lh',lh/100);document.body.classList.remove('dark','sepia');if(theme!=='light')document.body.classList.add(theme)}
$('menuBtn').onclick=openDrawer;$('overlay').onclick=()=>{closeDrawer();closeSheet();closeSettings()};$('settingsBtn').onclick=e=>{e.stopPropagation();$('settings').classList.toggle('show')};$('chapterPlayBtn').onclick=()=>startSpeech('chapter');$('allPlayBtn').onclick=()=>startSpeech('all');$('stopBtn').onclick=()=>stopSpeech();$('audioStop').onclick=()=>stopSpeech();$('audioToggle').onclick=toggleSpeech;$('speakWord').onclick=()=>selected&&speakText(selected.surface,.82);$('translateSentence').onclick=translateSentence;
$('knownBtn').onclick=()=>{if(!selected)return;const h=selected.head;if(known.has(h))known.delete(h);else known.add(h);localStorage.setItem('river.known',JSON.stringify([...known]));selected.el.classList.toggle('known',known.has(h));$('knownBtn').textContent=known.has(h)?'✓ 已学':'✓ 标记已学';updateStats()};$('favBtn').onclick=()=>{if(!selected)return;const h=selected.head;if(favs.has(h))favs.delete(h);else favs.add(h);localStorage.setItem('river.favs',JSON.stringify([...favs]));$('favBtn').textContent=favs.has(h)?'★ 已收藏':'☆ 收藏';updateStats()};
$('fontSize').oninput=e=>{document.documentElement.style.setProperty('--font',e.target.value+'px');localStorage.setItem('river.font',e.target.value)};$('lineHeight').oninput=e=>{document.documentElement.style.setProperty('--lh',e.target.value/100);localStorage.setItem('river.lh',e.target.value)};$('rate').oninput=e=>{$('rateText').textContent=(e.target.value/100).toFixed(2)+'×';localStorage.setItem('river.rate',e.target.value)};$('voice').onchange=e=>localStorage.setItem('river.voice',e.target.value);document.querySelectorAll('.theme-btn').forEach(b=>b.onclick=()=>{const t=b.dataset.theme;document.body.classList.remove('dark','sepia');if(t!=='light')document.body.classList.add(t);localStorage.setItem('river.theme',t)});
$('reader').addEventListener('click',e=>{const w=e.target.closest('.word');if(w)showWord(w)});window.addEventListener('scroll',()=>requestAnimationFrame(updateProgress),{passive:true});document.addEventListener('click',e=>{if(!e.target.closest('#settings')&&!e.target.closest('#settingsBtn'))closeSettings()});
CHAPTERS.forEach((c,i)=>{const b=document.createElement('button');b.className='chapter-btn';b.innerHTML=`<b>${i+1}.</b> ${escapeHtml(c.title.replace(/^Chapter\s+\w+\s+—\s+/i,''))}`;b.onclick=()=>{closeDrawer();renderChapter(i,false)};$('chapterList').appendChild(b)});
applyPrefs();renderChapter(chapterIndex,true);updateStats();loadDictionary();loadVoices();setTimeout(loadVoices,500);setTimeout(loadVoices,1500);speechSynthesis.onvoiceschanged=loadVoices;
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
