const CHAPTERS=[];const POLY={};const COLLOCATIONS=[];const SURFACE_HEAD={};const IPA_FALLBACK={};

// Verb forms are generated by Compromise's built-in English lexicon/inflection engine,
// not by a hand-written verb table in this project.
(()=>{
  const NLP_SRC='https://cdn.jsdelivr.net/npm/compromise@14.16.0/builds/compromise.min.js';
  let nlpReady=false;
  const lib=document.createElement('script');
  lib.src=NLP_SRC;
  lib.async=true;
  lib.onload=()=>{nlpReady=typeof window.nlp==='function'};
  lib.onerror=()=>{nlpReady=false};
  document.head.appendChild(lib);

  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clean=s=>String(s||'').replace(/^(?:has|have|had|is|am|are|was|were)\s+/i,'').trim();

  function ensureUI(){
    if(document.getElementById('verbSection'))return;
    const sense=document.getElementById('senseBox');
    if(!sense)return;
    const box=document.createElement('div');
    box.id='verbSection';
    box.style.display='none';
    box.innerHTML='<div class="section-title">动词变化</div><div id="verbForms" class="chips"></div><div id="verbSource" style="font:11px/1.4 -apple-system,BlinkMacSystemFont,\'Segoe UI\',sans-serif;color:var(--muted);margin-top:7px">词形由 Compromise 词形库生成</div>';
    sense.insertAdjacentElement('afterend',box);
  }

  function formByTransform(word,method){
    try{
      const d=window.nlp(word);
      const v=d.verbs();
      if(!v.found||typeof v[method]!=='function')return '';
      v[method]();
      return clean(d.text());
    }catch(e){return ''}
  }

  function formsFor(surface,sentence){
    if(typeof window.nlp!=='function')return {loading:true};
    try{
      const sentenceDoc=window.nlp(sentence||surface);
      const selected=sentenceDoc.match(surface);
      const isVerb=selected.found && selected.match('#Verb').found;
      if(!isVerb)return null;

      const raw=window.nlp(surface).verbs().conjugate();
      const c=Array.isArray(raw)&&raw.length?raw[0]:{};
      const pick=(...keys)=>{for(const k of keys){if(c&&c[k])return clean(c[k])}return ''};
      const infinitive=pick('Infinitive','infinitive')||formByTransform(surface,'toInfinitive')||surface.toLowerCase();
      const third=pick('PresentTense','presentTense','Present','present')||formByTransform(infinitive,'toPresentTense');
      const past=pick('PastTense','pastTense','Past','past')||formByTransform(infinitive,'toPastTense');
      const participle=pick('Participle','participle','PastParticiple','pastParticiple')||formByTransform(infinitive,'toPastParticiple');
      const gerund=pick('Gerund','gerund')||formByTransform(infinitive,'toGerund');
      if(!third&&!past&&!participle&&!gerund)return null;
      return {infinitive,third,past,participle,gerund};
    }catch(e){return null}
  }

  function hide(){ensureUI();const box=document.getElementById('verbSection');if(box)box.style.display='none'}
  function render(surface,sentence){
    ensureUI();
    const box=document.getElementById('verbSection'),target=document.getElementById('verbForms');
    if(!box||!target)return;
    const f=formsFor(surface,sentence);
    if(f&&f.loading){
      box.style.display='block';
      target.innerHTML='<span class="chip">词形库加载中…</span>';
      setTimeout(()=>{if(typeof window.nlp==='function')render(surface,sentence);else hide()},700);
      return;
    }
    if(!f){hide();return}
    const items=[['原形',f.infinitive],['三单',f.third],['过去式',f.past],['过去分词',f.participle],['-ing',f.gerund]].filter(x=>x[1]);
    target.innerHTML=items.map(([k,v])=>`<span class="chip"><b>${k}</b> ${esc(v)}</span>`).join('');
    box.style.display=items.length?'block':'none';
  }

  function bind(){
    ensureUI();
    const reader=document.getElementById('reader');
    if(!reader)return;
    reader.addEventListener('click',e=>{
      const w=e.target.closest('.word');
      if(!w)return;
      const surface=w.dataset.word||w.textContent||'';
      const sentence=w.closest('.sentence')?.dataset.text||'';
      setTimeout(()=>render(surface,sentence),0);
    });
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
